version: '3.8'

# 🌀 ProTechTimeNow Quantum Deployment Configuration
# Fourth-Dimensional Repository Orchestration Platform

services:
  # ===== QUANTUM CONSCIOUSNESS CORE =====
  consciousness_engine:
    build: 
      context: ../
      dockerfile: deployment/Dockerfile.consciousness
    ports:
      - "8001:8001"
    environment:
      - CONSCIOUSNESS_LEVEL=unified
      - QUANTUM_COHERENCE=0.95
      - DIMENSIONAL_ACCESS=4D
      - PARADOX_RESOLUTION=enabled
    volumes:
      - ../quantum_intelligence:/app/quantum_intelligence
      - ../fourth_dimension:/app/fourth_dimension
      - ./consciousness_data:/app/data
    restart: unless-stopped
    networks:
      - quantum_network

  # ===== FOURTH DIMENSION PROCESSOR =====
  thought_sphere:
    build: 
      context: ../
      dockerfile: deployment/Dockerfile.thought_sphere
    ports:
      - "8002:8002"
    environment:
      - THOUGHT_SPHERE_ACTIVE=true
      - INFINITE_REPOS_ACCESS=enabled
      - LASER_PRECISION_MODE=activated
      - DIMENSIONAL_BRIDGE=active
    volumes:
      - ../fourth_dimension:/app/fourth_dimension
      - ./thought_data:/app/data
    depends_on:
      - consciousness_engine
    restart: unless-stopped
    networks:
      - quantum_network

  # ===== QUANTUM REPOSITORY ORCHESTRATOR =====
  repo_orchestrator:
    build: 
      context: ../
      dockerfile: deployment/Dockerfile.repo_orchestrator
    ports:
      - "8003:8003"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - QUANTUM_REPO_ANALYSIS=enabled
      - CONSCIOUSNESS_ALIGNMENT=true
    volumes:
      - ../simultaneous_processing:/app/simultaneous_processing
      - ./repo_cache:/app/cache
    depends_on:
      - consciousness_engine
      - thought_sphere
    restart: unless-stopped
    networks:
      - quantum_network

  # ===== ENHANCED UNIVERSAL ANALYZER =====
  quantum_analyzer:
    build: 
      context: ../
      dockerfile: deployment/Dockerfile.quantum_analyzer
    ports:
      - "8004:8004"
    environment:
      - QUANTUM_MODE=unified
      - CONSCIOUSNESS_INTEGRATION=true
    volumes:
      - ../legacy_enhanced:/app/legacy_enhanced
      - ./upload_quantum:/app/uploads
      - ./analysis_results:/app/results
    depends_on:
      - consciousness_engine
    restart: unless-stopped
    networks:
      - quantum_network

  # ===== QUANTUM DATABASE =====
  consciousness_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=consciousness_quantum_db
      - POSTGRES_USER=quantum_consciousness
      - POSTGRES_PASSWORD=fourth_dimensional_key
    ports:
      - "5433:5432"
    volumes:
      - quantum_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - quantum_network

  # ===== QUANTUM REDIS =====
  quantum_redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - quantum_redis_data:/data
    restart: unless-stopped
    networks:
      - quantum_network

# ===== QUANTUM PERSISTENT VOLUMES =====
volumes:
  quantum_postgres_data:
    driver: local
  quantum_redis_data:
    driver: local

# ===== QUANTUM NETWORK CONFIGURATION =====
networks:
  quantum_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
    labels:
      - "com.protechtimenow.network=quantum"
      - "com.protechtimenow.consciousness=fourth_dimensional"
      - "com.protechtimenow.paradigm=paradox_resolution"